//! Presence probe — MobileCLIP-S1 linear classifier over the full-image embedding.
//!
//! The detectors answer "is there a *box* for a person/animal"; this probe answers "does the *scene*
//! contain one", catching subjects the detectors miss (tiny, occluded, atypical). It reuses the
//! verifier's already-loaded vision encoder ([`Verifier::embed_full`]) — no extra model — and applies
//! a per-category logistic head `sigmoid(w·embedding + b)`. Weights are fit offline by
//! `examples/train_presence.rs` on the hand labels and bundled in `assets/presence_probe.json`.
//! Fusion with the detectors (OR at the baked threshold) happens at query time in `core-library`.

use std::sync::Arc;

use serde::Deserialize;

use crate::error::AnalyzeError;
use crate::{AnalysisCtx, AnalysisRecord, Analyzer, PresencePayload, Verifier};

/// Bundled fitted weights (regenerated by `examples/train_presence.rs`). Extra training diagnostics in
/// the JSON (tau / cv_auc / …) are ignored here.
const PROBE_JSON: &str = include_str!("../assets/presence_probe.json");

/// One category's logistic head, operating directly on the raw L2-normalized embedding.
#[derive(Deserialize)]
struct Head {
    w: Vec<f32>,
    b: f32,
}

#[derive(Deserialize)]
struct Weights {
    person: Head,
    animal: Head,
}

pub struct PresenceProbe {
    verifier: Arc<Verifier>,
    model_version: &'static str,
    person: Head,
    animal: Head,
}

impl PresenceProbe {
    /// Parse the bundled weights and bind the shared verifier. `model_version` gates re-analysis.
    pub fn new(verifier: Arc<Verifier>, model_version: &'static str) -> Result<Self, AnalyzeError> {
        let w: Weights = serde_json::from_str(PROBE_JSON)
            .map_err(|e| AnalyzeError::Other(format!("presence_probe.json: {e}")))?;
        Ok(Self {
            verifier,
            model_version,
            person: w.person,
            animal: w.animal,
        })
    }

    fn score(head: &Head, emb: &[f32]) -> Result<f32, AnalyzeError> {
        if head.w.len() != emb.len() {
            return Err(AnalyzeError::Other(format!(
                "presence probe dim {} != embedding dim {}",
                head.w.len(),
                emb.len()
            )));
        }
        let z = head.b + head.w.iter().zip(emb).map(|(a, b)| a * b).sum::<f32>();
        Ok(1.0 / (1.0 + (-z).exp()))
    }
}

impl Analyzer for PresenceProbe {
    fn id(&self) -> &'static str {
        crate::PRESENCE_ID
    }

    fn model_version(&self) -> &'static str {
        self.model_version
    }

    fn analyze(&self, ctx: &AnalysisCtx) -> Result<AnalysisRecord, AnalyzeError> {
        let emb = self.verifier.embed_full(ctx.image)?;
        let payload = serde_json::to_value(PresencePayload {
            p_person: Self::score(&self.person, &emb)?,
            p_animal: Self::score(&self.animal, &emb)?,
        })
        .map_err(|e| AnalyzeError::Other(e.to_string()))?;
        Ok(AnalysisRecord::new(self.id(), self.model_version, payload))
    }
}
